id: A4CF454C2
title: Daily Practice of Guru Rinpoche, Buddha of Medicine
type: translation
pechas:
- IE7D2B3B9
- I03030C03
- IA8DDD18C
source_metadata:
  languages:
  - en
  - fr
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:05.619893
  last_modified_at: 2023-01-04 11:39:05.619897
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IE7D2B3B9/EE0F: CD9F
  I03030C03/E8A9: CD9F
  IA8DDD18C/8934: CD9F
